name: 'Veracode Static scanning flaw importer'
description: 'Download static scan findings and create GitHub Security issues'
inputs:
  app_name:
    description: 'The applications name'
    required: true
  app_guid:
    description: 'The applications API GUID'
    required: false
  sandbox_name:
    description: 'The sandboxname'
    required: false
  sandbox_guid:
    description: "The sandbox guid'
    required: false
  scantype:
    description: 'the type of scan'
    required: false
    default: 'STATIC'
  includeannotations:  
    description: 'Include annotations'
    required: false
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.guid }}
    - ${{ inputs.scantype }}
    - ${{ inputs.importtype }}
    - ${{ inputs.includeannotations }}
